### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by gnbl** [pklaus/ds1054z#6]
Hi,
I'm pretty sure the file ds1054z/ds1054z/resources/overlay.png was made by me (https://github.com/gnbl/DS1000Z/blob/master/overlay100.png) and you seem to be using/re-publishing it without any attribution (and strictly speaking, nor explicit permission, since I haven't licensed it)!
That's not very nice.

**Comment by gnbl** [comment]
Never mind: https://github.com/pklaus/ds1054z/commit/f1fa30dcbed49cbfaacc81c86d664b1417413352#diff-18f44a8ad821a1eaabc32270a7b60b65

**Comment by pklaus** [comment]
Sorry, you're right. I should have asked you for permission / the license.
Would it be OK, if I mention you / DS1000Z in the resources section: <https://github.com/pklaus/ds1054z#resources>?

**Comment by gnbl** [comment]
Thanks, no need, the original commit message suffices. Will try your tool soon, all the necessary drivers are a pain.
